project_id = "eekfcjpoyfcuzvvsgwaw"

[functions.flutterwave-transfer]
verify_jwt = true

[functions.iyanjuPay-transfer]
verify_jwt = true

[functions.flutterwave-banks]
verify_jwt = true

[functions.resolve-bank-account]
verify_jwt = true

[functions.flutterwave-sync-deposits]
verify_jwt = true

[functions.flutterwave-bills]
verify_jwt = true

[functions.flutterwave-card]
verify_jwt = true

[functions.flutterwave-bvn]
verify_jwt = true
