import{corsHeaders,json,adminClient,getUser}from'../_shared/auth.ts';
import{get,post,rows,id,name,provider,price,sell,ceil10,status,msg,pref}from'../_shared/topupmate.ts';
type O=Record<string,any>;const MARKUP=3;const NO=new Set(['airtime','airtime-card','recharge-card','electricity']);const s=(v:any)=>String(v??'').trim();const n=(v:any)=>Number.isFinite(Number(v))?Number(v):0;const ref=()=>`TPM_${crypto.randomUUID().replace(/-/g,'')}`;
function network(v:any){const x=s(v).toLowerCase();return({mtn:'1','1':'1',airtel:'2','2':'2',glo:'3','3':'3','9mobile':'4','9 mobile':'4','4':'4',etisalat:'4'}as any)[x]??x}
function cable(v:any){const x=s(v).toLowerCase();if(x.includes('gotv')||x==='1')return'1';if(x.includes('dstv')||x==='2')return'2';if(x.includes('startimes')||x.includes('startime')||x==='3')return'3';return s(v)}
function cableName(v:any){const x=s(v).toLowerCase();if(x.includes('gotv')||x==='1')return'GOtv';if(x.includes('dstv')||x==='2')return'DStv';if(x.includes('startimes')||x.includes('startime')||x==='3')return'StarTimes';return s(v)}
function internetKey(v:any){const x=s(v).toLowerCase().replace(/[^a-z0-9]+/g,'');if(x.includes('smile'))return'smile';if(x.includes('alpha'))return'alpha';if(x.includes('kirani'))return'kirani';if(x.includes('ratel'))return'ratel';return x}
function internetService(v:any){const x=internetKey(v);return({smile:'smile',alpha:'alpha',kirani:'kirani',ratel:'ratel'}as any)[x]??x}
function extractRows(body:any){const direct=rows(body);if(direct.length)return direct;for(const k of ['items','products','plans','packages','services','providers','billers','giftcards','gift_cards','cards','available']){if(Array.isArray(body?.[k]))return body[k];if(Array.isArray(body?.data?.[k]))return body.data[k];}if(body?.data&&typeof body.data==='object'&&!Array.isArray(body.data)){for(const v of Object.values(body.data)){if(Array.isArray(v))return v;}}return [];}
function disco(v:any){const x=s(v).toLowerCase();return({"1":'IE',"2":'EKEDC',"3":'KEDCO',"4":'PHEDC',"5":'JED',"6":'IBEDC',"7":'KEDC',"8":'AEDC',"9":'ENUGU',"10":'BENIN',"11":'YOLA',ikeja:'IE','ikeja electric':'IE',eko:'EKEDC','eko electric':'EKEDC',kano:'KEDCO','kano electric':'KEDCO','port harcourt':'PHEDC','port harcourt electric':'PHEDC',jos:'JED','jos electric':'JED',ibadan:'IBEDC','ibadan electric':'IBEDC',kaduna:'KEDC','kaduna electric':'KEDC',abuja:'AEDC','abuja electric':'AEDC',enugu:'ENUGU','enugu electric':'ENUGU',benin:'BENIN','benin electric':'BENIN',yola:'YOLA','yola electric':'YOLA'}as any)[x]??s(v).toUpperCase()}
function catService(service:string,body:O={}){if(service==='airtime'||service==='data')return'network';if(service==='cable')return (body.provider||body.provider_name||body.biller_code)?'cabletv':'cable-provider';if(service==='electricity')return'electricity';if(['education','jamb','waec','neco','nabteb'].includes(service))return'exampin';if(['airtime-card','recharge-card'].includes(service))return'recharge-card';if(service==='data-card')return'datapin';if(['internet','smile','alpha','kirani','ratel'].includes(service))return internetService(body.provider_name||body.provider||service);if(service==='gift-card')return'giftcard';return service;}
function norm(service:string,r:any){const p=price(r),m=NO.has(service)?0:MARKUP,i=id(r),nm=name(r),pr=provider(r);return{id:i,code:i,plan_id:i,name:nm,display_name:nm,provider:pr,provider_name:pr,network:pr,network_name:pr,providerPrice:p,provider_price:p,selling_price:p?sell(p,m):0,price:p?sell(p,m):0,amount:p?sell(p,m):0,validity:r?.validity??r?.duration??r?.period??null,plan_type:r?.plan_type??r?.planType??r?.type??null,raw:r};}
async function billers(service:string){
 if(service==='internet'){
  return{success:true,service,billers:[
   {id:'smile',code:'smile',name:'Smile',display_name:'Smile',provider_name:'Smile',provider_service:'smile'},
   {id:'alpha',code:'alpha',name:'Alpha',display_name:'Alpha',provider_name:'Alpha',provider_service:'alpha'},
   {id:'kirani',code:'kirani',name:'Kirani',display_name:'Kirani',provider_name:'Kirani',provider_service:'kirani'},
   {id:'ratel',code:'ratel',name:'Ratel',display_name:'Ratel',provider_name:'Ratel',provider_service:'ratel'}
  ],items:[],plans:[],packages:[]};
 }
 if(service==='education'){
  return{success:true,service,billers:[
   {id:'jamb',code:'jamb',name:'JAMB',display_name:'JAMB',provider_name:'JAMB',provider_service:'jamb'},
   {id:'waec',code:'waec',name:'WAEC',display_name:'WAEC',provider_name:'WAEC',provider_service:'waec'},
   {id:'neco',code:'neco',name:'NECO',display_name:'NECO',provider_name:'NECO',provider_service:'neco'},
   {id:'nabteb',code:'nabteb',name:'NABTEB',display_name:'NABTEB',provider_name:'NABTEB',provider_service:'nabteb'}
  ],items:[],plans:[],packages:[]};
 }
 if(service==='recharge-card'){
  return{success:true,service,billers:[
   {id:'1',code:'1',name:'MTN',display_name:'MTN',provider_name:'MTN',network_name:'MTN'},
   {id:'2',code:'2',name:'Airtel',display_name:'Airtel',provider_name:'Airtel',network_name:'Airtel'},
   {id:'3',code:'3',name:'Glo',display_name:'Glo',provider_name:'Glo',network_name:'Glo'},
   {id:'4',code:'4',name:'9mobile',display_name:'9mobile',provider_name:'9mobile',network_name:'9mobile'}
  ],items:[],plans:[],packages:[]};
 }
 if(service==='recharge-card'){
  const c=await get('/services/',{service:'recharge-card'});if(!c.ok||status(c.body)==='fail')throw new Error(msg(c.body));const a=extractRows(c.body);const wanted=s(b.provider_name||b.provider||b.network_name||b.network||b.biller_code).toLowerCase();const wn=({1:'mtn',2:'airtel',3:'glo',4:'9mobile'}as any)[wanted]??wanted;const items=a.map(r=>norm(service,r)).filter((r:any)=>{if(!wn)return true;const raw=JSON.stringify(r.raw||{}).toLowerCase();const rp=r.provider.toLowerCase();const rn=r.name.toLowerCase();return rp.includes(wn)||rn.includes(wn)||raw.includes(wn);});return{success:true,service,billers:[],items,plans:items,packages:items};
 }
 if(service==='gift-card'){
  const c=await get('/giftcard/available/',{countryCode:'NG'});if(!c.ok||status(c.body)==='fail')throw new Error(msg(c.body));
  const a=extractRows(c.body);const providers:any[]=[];const seen=new Set<string>();
  for(const r of a){const pr=s(r?.provider??r?.brand??r?.brand_name??r?.name??r?.title);const code=s(r?.provider_code??r?.brand_code??r?.code??r?.id);const key=(code||pr).toLowerCase();if(!key||seen.has(key))continue;seen.add(key);providers.push({id:code||pr,code:code||pr,name:pr||code,display_name:pr||code,provider:pr,provider_name:pr,raw:r});}
  return{success:true,service,billers:providers,items:a.map((r:any)=>norm(service,r)),plans:a.map((r:any)=>norm(service,r)),packages:a.map((r:any)=>norm(service,r))};
 }
 const c=await get('/services/',{service:catService(service)});if(!c.ok||status(c.body)==='fail')throw new Error(msg(c.body));const st=await get('/status/');const sb=st.body||{};let a=extractRows(c.body);if(['cable','electricity'].includes(service)){const z=service==='cable'?sb.cable:sb.electricity;if(Array.isArray(z)&&z.length)a=z;}a=a.filter((r:any)=>{const st=s(r?.status).toLowerCase();return !['inactive','off','disabled','unavailable'].includes(st)});return{success:true,service,billers:a.map((r:any)=>({id:String(r?.networkid??r?.id??r?.provider??r?.network??''),code:String(r?.networkid??r?.id??r?.provider??r?.network??''),name:name(r)||provider(r),display_name:name(r)||provider(r),network_name:r?.network,provider_name:r?.providerName??r?.provider_name??r?.provider,status:r?.status??'active',successPercentage:r?.successPercentage,discount:r?.discount,raw:r})),items:[],plans:[],packages:[]};}
async function catalog(service:string,b:O){
 if(service==='gift-card'){
  const c=await get('/giftcard/available/',{countryCode:'NG'});if(!c.ok||status(c.body)==='fail')throw new Error(msg(c.body));const a=extractRows(c.body);const wanted=s(b.provider_name||b.provider||b.biller_code).toLowerCase();const items=a.map(r=>norm(service,r)).filter((r:any)=>{if(!wanted)return true;const raw=JSON.stringify(r.raw||{}).toLowerCase();return raw.includes(wanted)||r.provider.toLowerCase()===wanted||r.name.toLowerCase().includes(wanted);});return{success:true,service,billers:[],items,plans:items,packages:items};
 }
 const providerKey=service==='internet'?internetService(b.provider_name||b.provider||b.biller_code||b.network):service;
 const c=await get('/services/',{service:catService(providerKey,b)});if(!c.ok||status(c.body)==='fail')throw new Error(msg(c.body));const a=extractRows(c.body);if(service==='cable'&&!b.provider_name&&!b.biller_code)return{success:true,service,billers:a.map((r:any)=>({id:id(r),code:id(r),name:name(r)||provider(r),display_name:name(r)||provider(r),provider:provider(r),raw:r})),items:[],plans:[],packages:[]};
 const wanted=s(b.provider_name||b.network_name||b.network||b.biller_code).toLowerCase();const wantedName=service==='data'?({1:'mtn',2:'airtel',3:'glo',4:'9mobile'} as any)[wanted]??wanted:wanted;
 const items=a.map(r=>norm(service,r)).filter((r:any)=>{if(!wantedName)return true;const w=wantedName.replace(/[^a-z0-9]+/g,'');const rp=r.provider.toLowerCase().replace(/[^a-z0-9]+/g,'');const rn=r.name.toLowerCase();const raw=JSON.stringify(r.raw||{}).toLowerCase();return rp===w||rn.includes(wantedName)||raw.includes(wantedName);});
 return{success:true,service,billers:[],items,plans:items,packages:items};}
async function verify(service:string,b:O){
 if(service==='cable'){const p=cable(b.provider_name??b.provider??b.biller_code??b.cable_tv),i=s(b.iuc??b.smartcard_number??b.smartcard_no??b.customer);if(!p||!/^[0-9]{8,20}$/.test(i))throw new Error('Enter a valid IUC / SmartCard number.');const r=await post('/cable/verify/',{provider:p,iucnumber:i});if(!r.ok||status(r.body)==='fail')throw new Error(msg(r.body));const d=r.body?.response??r.body?.data??r.body,nm=s(r.body?.name??r.body?.Customer_Name??d?.name??d?.customer_name??d?.customerName??d?.subscriber_name??r.body?.msg);if(!nm)throw new Error('Unable to verify this SmartCard number.');return{success:true,customer_name:nm,customerName:nm,message:'Customer verified successfully.',provider_response:r.body};}
 if(service==='electricity'){const p=disco(b.biller_code??b.provider??b.disco),m=s(b.meter??b.meter_number??b.customer),t=s(b.meter_type??b.meterType??'prepaid').toLowerCase();if(!p||!m||!['prepaid','postpaid'].includes(t))throw new Error('Meter details are required.');const r=await post('/electricity/verify/',{provider:p,meternumber:m,metertype:t});if(!r.ok||status(r.body)==='fail')throw new Error(msg(r.body));const d=r.body?.response??r.body?.data??r.body,nm=s(r.body?.name??r.body?.Customer_Name??d?.name??d?.customer_name??d?.customerName??d?.customer_name_on_meter??r.body?.msg);return{success:true,customer_name:nm,customerName:nm,message:'Meter verified successfully.'};}
 throw new Error('Verification is not required for this service.');}
async function update(a:any,u:string,r:string,x:O){const{error}=await a.from('transactions').update(x).eq('user_id',u).eq('reference_number',r);if(error)console.error('Topupmate transaction update failed',error);}
async function refund(a:any,u:string,amt:number,r:string,m:O){return a.rpc('refund_wallet',{_user_id:u,_amount:amt,_description:'Topupmate service reversal',_idempotency_key:`REFUND_${r}`,_reference:`REFUND_${r}`,_metadata:m});}
async function purchase(a:any,u:any,b:O){const service=s(b.service??b.type).toLowerCase(),d=b.details??b,r=s(b.idempotency_key??b.idempotencyKey)||ref(),item=d.item??{},customer=s(d.customer??d.phone??d.mobile_number??d.phoneNumber??d.account_id);let pAmt=0,sAmt=0,path='',body:O={};
if(service==='airtime'){const net=network(d.network_code??d.networkId??d.biller_code??d.network);pAmt=n(d.amount??b.amount);if(!net||!/^[0-9]{11}$/.test(customer)||pAmt<50)throw new Error('Enter a valid phone number, network and airtime amount.');path='/airtime/';body={network:net,phone:customer,amount:pAmt,airtime_type:'VTU',ref:r};sAmt=pAmt;}
else if(service==='data'){const net=network(d.network_code??d.networkId??d.biller_code??d.network),plan=s(d.item_code??d.plan_code??item.id??item.code);if(!net||!/^[0-9]{11}$/.test(customer)||!plan)throw new Error('Network, phone number and data plan are required.');path='/data/';body={network:net,phone:customer,plan,ref:r};pAmt=n(item.providerPrice??item.provider_price??item.price);if(!pAmt){const c=await get('/services/',{service:'data'});const f=rows(c.body).find((x:any)=>id(x)===plan);pAmt=price(f);}if(!pAmt)throw new Error('The selected data plan is unavailable.');sAmt=sell(pAmt,3);}
else if(service==='cable'){const pr=cable(d.provider_name??d.providerName??d.biller_code??d.cable_tv),i=s(d.smartcard_number??d.smartcardNumber??d.smartcard_no??d.customer),plan=s(d.item_code??d.plan_code??item.id??item.code);if(!pr||!/^[0-9]{8,20}$/.test(i)||!plan)throw new Error('Cable provider, SmartCard number and package are required.');path='/cabletv/';body={provider:pr,iucnumber:i,plan,ref:r,subtype:s(d.subtype??'renew')||'renew',phone:customer||undefined};pAmt=n(item.providerPrice??item.provider_price??item.price);if(!pAmt){const c=await get('/services/',{service:'cabletv'});pAmt=price(rows(c.body).find((x:any)=>id(x)===plan));}if(!pAmt)throw new Error('The selected cable package is unavailable.');sAmt=sell(pAmt,3);}
else if(service==='electricity'){const pr=disco(d.biller_code??d.provider??d.disco),m=s(d.meter_number??d.meter??d.customer),t=s(d.meter_type??d.meterType??'prepaid').toLowerCase();pAmt=n(d.provider_amount??d.amount??b.amount);if(!pr||!m||!['prepaid','postpaid'].includes(t)||pAmt<=0)throw new Error('Electricity provider, meter type, meter number and amount are required.');path='/electricity/';body={provider:pr,meternumber:m,amount:pAmt,metertype:t,phone:customer||undefined,ref:r};sAmt=pAmt;}
else if(['education','jamb','waec','neco','nabteb'].includes(service)){const pr=s(d.provider??d.provider_name??d.biller_code??'WAEC').toUpperCase(),q=Math.max(1,Math.floor(n(d.quantity??1)));path='/exampin/';body={provider:pr,quantity:q,ref:r};pAmt=n(item.providerPrice??item.provider_price??item.price);if(!pAmt){const c=await get('/services/',{service:'exampin'});pAmt=price(rows(c.body).find((x:any)=>id(x)===s(d.item_code??item.id)));}if(!pAmt)throw new Error('The selected education PIN is unavailable.');sAmt=sell(pAmt,3)*q;}
else if(service==='airtime-card'||service==='recharge-card'){const net=network(d.network_code??d.networkId??d.biller_code??d.network),plan=s(d.item_code??item.id??item.code),q=Math.max(1,Math.floor(n(d.quantity??1)));if(!net||!plan)throw new Error('Network and airtime PIN denomination are required.');path='/rechargepin/';body={network:net,quantity:q,plan,businessname:s(d.businessname??'IyanjuPay'),ref:r};pAmt=n(item.providerPrice??item.provider_price??item.price);if(!pAmt){const c=await get('/services/',{service:'recharge-card'});pAmt=price(rows(c.body).find((x:any)=>id(x)===plan));}if(!pAmt)throw new Error('The selected recharge PIN is unavailable.');sAmt=pAmt*q;}
else if(service==='data-card'){const net=network(d.network_code??d.networkId??d.biller_code??d.network),plan=s(d.item_code??item.id??item.code),q=Math.max(1,Math.floor(n(d.quantity??1)));if(!net||!plan)throw new Error('Network and data PIN plan are required.');path='/datapin/';body={network:net,quantity:q,data_plan:plan,businessname:s(d.businessname??'IyanjuPay'),ref:r};pAmt=n(item.providerPrice??item.provider_price??item.price);if(!pAmt){const c=await get('/services/',{service:'datapin'});pAmt=price(rows(c.body).find((x:any)=>id(x)===plan));}if(!pAmt)throw new Error('The selected data PIN is unavailable.');sAmt=sell(pAmt,3)*q;}
else if(service==='internet'||service==='smile'||service==='alpha'||service==='kirani'||service==='ratel'){const ik=internetService(d.provider_name??d.provider??d.biller_code??d.service??service),plan=s(d.item_code??d.plan_code??item.id??item.code),acct=s(d.account_number??d.accountNumber??d.account_id??d.customer);if(!plan||!acct)throw new Error('Internet account and plan are required.');if(ik==='smile'){path='/smile-data/';body={PhoneNumber:acct,BundleTypeCode:plan,actype:s(d.account_type??'prepaid')};}else if(ik==='alpha'){path='/alphatopup/';body={phone:acct,plan,ref:r};}else if(ik==='kirani'){path='/kirani/';body={phone:acct,plan,ref:r};}else{path='/ratel/';body={phone:acct,plan,ref:r};}pAmt=n(item.providerPrice??item.provider_price??item.price);if(!pAmt){const c=await get('/services/',{service:ik});pAmt=price(extractRows(c.body).find((x:any)=>id(x)===plan));}if(!pAmt)throw new Error('The selected internet plan is unavailable.');sAmt=sell(pAmt,3);}
else throw new Error('This service is not available through Topupmate.');
const meta={provider:'topupmate',provider_path:path,provider_amount:pAmt,selling_amount:sAmt,service,request_id:r,customer:customer||null,provider_catalog_id:s(item.id??d.item_code)||null};const debit=await a.rpc('debit_wallet',{_user_id:u.id,_amount:sAmt,_description:`${service} purchase`,_idempotency_key:r,_reference:r,_category:'bill_payment',_metadata:meta});if(debit.error)throw new Error('Unable to process the payment from your wallet.');const tx=debit.data?.id??null;await update(a,u.id,r,{status:'pending',provider:'topupmate',provider_reference:r,transaction_type:service,metadata:meta});let pr;try{const q=await post(path,body);pr=q.body;if(!q.ok&&status(pr)!=='processing'){const rr=await refund(a,u.id,sAmt,r,{...meta,provider_response:pr});await update(a,u.id,r,{status:'failed',provider:'topupmate',provider_reference:pref(pr)??r,metadata:{...meta,provider_response:pr,refunded:!rr.error}});throw new Error('Purchase failed. Your wallet has been refunded.');}}catch(e){if(e instanceof Error&&e.message.includes('refunded'))throw e;await update(a,u.id,r,{status:'pending',provider:'topupmate',provider_reference:r,metadata:{...meta,reconciliation_required:true,pending_reason:'provider_transport_failure'}});return{success:true,status:'pending',reference:r,transaction_reference:r,transaction_id:tx,message:'Your payment is being verified. Please wait while we confirm the provider result.'};}const st=status(pr),pRef=pref(pr)??r;if(st==='fail'){const rr=await refund(a,u.id,sAmt,r,{...meta,provider_response:pr});await update(a,u.id,r,{status:'failed',provider:'topupmate',provider_reference:pRef,metadata:{...meta,provider_response:pr,refunded:!rr.error}});throw new Error('Purchase failed. Your wallet has been refunded.');}if(st==='processing'){await update(a,u.id,r,{status:'pending',provider:'topupmate',provider_reference:pRef,metadata:{...meta,provider_response:pr,reconciliation_required:true,pending_reason:'provider_processing'}});return{success:true,status:'pending',reference:r,transaction_reference:r,transaction_id:tx,provider_reference:pRef,message:'Your payment is being processed.'};}await update(a,u.id,r,{status:'success',provider:'topupmate',provider_reference:pRef,metadata:{...meta,provider_response:pr}});return{success:true,status:'success',reference:r,transaction_reference:r,transaction_id:tx,provider_reference:pRef,provider_data:pr?.response??pr?.data??null,message:'Purchase completed successfully.'};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({success:false,error:'Method not allowed.'},405);const u=await getUser(req);if(!u)return json({success:false,error:'Authentication required.'},401);const a=adminClient();let b:O={};try{b=await req.json()}catch{return json({success:false,error:'Invalid request body.'},400)}const ac=s(b.action).toLowerCase();try{if(ac==='billers')return json(await billers(s(b.service).toLowerCase()));if(ac==='catalog'||ac==='get_catalog')return json(await catalog(s(b.service).toLowerCase(),b));if(ac==='verify_customer'||ac==='verify')return json(await verify(s(b.service).toLowerCase(),b));if(ac==='purchase')return json(await purchase(a,u,b));if(ac==='transaction_status'||ac==='status'){const r=s(b.reference??b.transaction_reference??b.transref);if(!r)throw new Error('Transaction reference is required.');const q=await get('/transaction/status/',{reference:r});if(!q.ok)throw new Error(msg(q.body));return json({success:true,status:status(q.body),reference:r,transaction:q.body});}if(ac==='wallet'){const q=await get('/user/');if(!q.ok)throw new Error(msg(q.body));return json({success:true,wallet:q.body});}if(ac==='notifications'){const q=await get('/notification/');if(!q.ok)throw new Error(msg(q.body));return json({success:true,notifications:q.body?.notifications??[]});}if(ac==='transactions'){const q=await get('/transaction/',b.params??{});if(!q.ok)throw new Error(msg(q.body));return json({success:true,...q.body});}throw new Error('Unsupported service request.');}catch(e:any){console.error('Topupmate service error',{action:ac,service:b.service,user_id:u.id,error:e});return json({success:false,error:String(e?.message??'Service request failed.')},400)}});
